/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Dao.DBConnect;
import Dao.DaoNhanVien;
import Dao.HopDongDao;
import Dao.PhongBanDao;
import Dao.TimKiemDao;
import Model.HopDong;
import Model.NhanVien;
import Model.PhongBan;
import java.awt.Dimension;
import java.awt.Font;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author TVD
 */
public class HopDongJPanel extends javax.swing.JPanel {
    private TableRowSorter<TableModel> rowSorter = null;
        HopDongDao tt=new HopDongDao();
       
 DefaultTableModel dtmhd;
 HopDong hopDong=new HopDong();
  JFileChooser filechooser;
    /**
     * Creates new form KhoaHocJPanel
     */ 
 DefaultTableModel dtmluong;
    public HopDongJPanel() {
        
        initComponents();
         filechooser=new JFileChooser();
         filechooser.setFileFilter(new FileFilter() {
            @Override
            public boolean accept(File f) {
                return f.getAbsolutePath().endsWith(".xlsx");
            }
            @Override
            public String getDescription() {
                   return "node .xlsx";
            }
        }); 
               dtmhd=(DefaultTableModel) this.tblHopDong.getModel();
                hienthi();
             
                 rowSorter = new TableRowSorter<>(tblHopDong.getModel());
        tblHopDong.setRowSorter(rowSorter);
        tblHopDong.getColumnModel().getColumn(0).setMinWidth(150);
        tblHopDong.getColumnModel().getColumn(0).setMaxWidth(150);
        tblHopDong.getColumnModel().getColumn(0).setPreferredWidth(150);
        
        tblHopDong.getColumnModel().getColumn(1).setMinWidth(150);
        tblHopDong.getColumnModel().getColumn(1).setMaxWidth(150);
        tblHopDong.getColumnModel().getColumn(1).setPreferredWidth(150);
        
         tblHopDong.getTableHeader().setFont(new Font("Arrial", Font.BOLD, 14));
        tblHopDong.getTableHeader().setPreferredSize(new Dimension(100, 50));
        tblHopDong.setRowHeight(50);
        tblHopDong.validate();
        tblHopDong.repaint();  
      
    
    
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHopDong = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jtfSerach = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btntim = new javax.swing.JButton();
        btnhienthi = new javax.swing.JButton();
        btnthem = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 255, 0));

        tblHopDong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Hợp Đồng", "Mã Nhân Viên", "Loại Hợp Đồng", "Ngày Bắt Đầu", "Ngày Kết Thúc", "Tình Trạng"
            }
        ));
        tblHopDong.setToolTipText("");
        tblHopDong.setDropMode(javax.swing.DropMode.ON);
        tblHopDong.getTableHeader().setResizingAllowed(false);
        tblHopDong.getTableHeader().setReorderingAllowed(false);
        tblHopDong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHopDongMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblHopDongMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(tblHopDong);

        jtfSerach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSerachActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Tìm NV Theo  Hợp Đồng");

        btntim.setBackground(new java.awt.Color(51, 255, 0));
        btntim.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btntim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-zoom-in-34.png"))); // NOI18N
        btntim.setText("Tìm");
        btntim.setBorder(null);
        btntim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimActionPerformed(evt);
            }
        });

        btnhienthi.setBackground(new java.awt.Color(204, 255, 204));
        btnhienthi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnhienthi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-eye-35.png"))); // NOI18N
        btnhienthi.setText("Hiển Thị");
        btnhienthi.setBorder(null);
        btnhienthi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhienthiActionPerformed(evt);
            }
        });

        btnthem.setBackground(new java.awt.Color(255, 255, 153));
        btnthem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnthem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-insert-page-32.png"))); // NOI18N
        btnthem.setText("Thêm HD");
        btnthem.setBorder(null);
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setText("Xuất File EXcel");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1078, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(jLabel3)
                        .addContainerGap(729, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnhienthi, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btntim, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jtfSerach, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfSerach, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(133, 133, 133)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnhienthi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btntim, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Dach Sách Hợp Đồng", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

    }//GEN-LAST:event_formComponentShown

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
        // TODO add your handling code her:

    }//GEN-LAST:event_jPanel1ComponentShown

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
            ThemHdJdalog tt=new ThemHdJdalog();
            tt.setTitle("Thêm Hóa Đơn");
            tt.setResizable(false);
            tt.setVisible(true);
            tt.setLocationRelativeTo(null);
                     
            
                
            
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnhienthiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhienthiActionPerformed
        // TODO add your handling code here:
        hienthi();
        
       
    }//GEN-LAST:event_btnhienthiActionPerformed

    private void btntimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimActionPerformed
        if(jtfSerach.getText().length()>0)
        {
            hienthi2();
//            String timkiemString=jtfSerach.getText();
//            ArrayList<HopDong> list=HopDongDao.gethienthiCSDL(timkiemString);
//            dtmhd=(DefaultTableModel) tblHopDong.getModel();
//            dtmhd.setRowCount(0);
//            for(HopDong hd:list)
//            {
//                Vector<Object>vec=new Vector<>();
//                vec.add(hd.getMAHD());
//                vec.add(hd.getMaNV());
//                vec.add(hd.getLoaiHD());
//                vec.add(hd.getNgayBD());
//                vec.add(hd.getNgayKT());
//                vec.add(hd.isTinhTrang()== true ? "Còn" : "Nghĩ");
//                dtmhd.addRow(vec);
//            }
//
//            tblHopDong.setModel(dtmhd);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "bạn chưa nhập dữ liệu cần tìm");
        }

    }//GEN-LAST:event_btntimActionPerformed

    private void jtfSerachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSerachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSerachActionPerformed

    private void tblHopDongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHopDongMouseClicked
    int selectedRowIndex = tblHopDong.getSelectedRow();
        selectedRowIndex = tblHopDong.convertRowIndexToModel(selectedRowIndex);

        hopDong.setMAHD(tblHopDong.getValueAt(selectedRowIndex,0)+"");
        hopDong.setMaNV(tblHopDong.getValueAt(selectedRowIndex,1)+"");
        hopDong.setLoaiHD(tblHopDong.getValueAt(selectedRowIndex,2)+"");
        hopDong.setNgayBD(tblHopDong.getValueAt(selectedRowIndex,3)+"");
        hopDong.setNgayKT(tblHopDong.getValueAt(selectedRowIndex,4)+"");
        hopDong.setTinhTrang(tblHopDong.getValueAt(selectedRowIndex,5).toString().equalsIgnoreCase("Còn"));
        SuaHopDong framDong=new SuaHopDong(hopDong);
        framDong.setVisible(true);
        framDong.setTitle("Xóa Sữa Hợp Đồng");
        framDong.setLocationRelativeTo(null);
    }//GEN-LAST:event_tblHopDongMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
      xuatFileExcel();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tblHopDongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHopDongMouseEntered
      
  
        
        
        
    }//GEN-LAST:event_tblHopDongMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhienthi;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btntim;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jtfSerach;
    private javax.swing.JTable tblHopDong;
    // End of variables declaration//GEN-END:variables

   
  public void xuatFileExcel(){
      
            XSSFWorkbook workbook = new XSSFWorkbook();
            XSSFSheet sheet = workbook.createSheet("Hợp Đồng");
            
            XSSFRow row = null;
            Cell cell = null;
            
            row = sheet.createRow(0);
            
            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("STT");
            
            cell = row.createCell(1, CellType.STRING);
            cell.setCellValue("Mã Hóa Đơn");
            
            cell = row.createCell(2, CellType.STRING);
            cell.setCellValue("Mã Nhân Viên");
            
            cell = row.createCell(3, CellType.STRING);
            cell.setCellValue("Loại Hợp Đồng");
            
            cell = row.createCell(4, CellType.STRING);
            cell.setCellValue("Ngày Bắt Đầu");
            
            cell = row.createCell(5, CellType.STRING);
            cell.setCellValue("Ngày Kết Thúc");
            
            cell = row.createCell(6, CellType.STRING);
            cell.setCellValue("Tình Trạng");
            
           
            
            ArrayList<HopDong> listItem=HopDongDao.laydachsachhd();

if (listItem != null) {
    
    try {
        int s = listItem.size();
        for (int i = 0; i < s; i++) {
            hopDong= listItem.get(i);
            this.hopDong=hopDong;
            row = sheet.createRow(1 + i);
            
            
            cell = row.createCell(0, CellType.NUMERIC);
            cell.setCellValue(i + 1);
            
            cell = row.createCell(1, CellType.STRING);
            cell.setCellValue(hopDong.getMAHD());
            
            cell = row.createCell(2, CellType.STRING);
            cell.setCellValue(hopDong.getMaNV());
            
            cell = row.createCell(3, CellType.STRING);
            cell.setCellValue(hopDong.getLoaiHD());
            
            cell = row.createCell(4, CellType.STRING);
            cell.setCellValue(hopDong.getNgayBD());
            
            cell = row.createCell(5, CellType.STRING);
            cell.setCellValue(hopDong.getNgayKT());
            
            cell = row.createCell(6, CellType.STRING);
            cell.setCellValue(hopDong.isTinhTrang()? "còn" : "Nghĩ");
            
           
        }
        // save file
        
    } catch (Exception ex) {
        ex.printStackTrace();
    }
}
  if(filechooser.showSaveDialog(null)==JFileChooser.APPROVE_OPTION){
                try {
                    FileOutputStream fis = null;
                    File f = new File(filechooser.getSelectedFile().toString());
                    fis = new FileOutputStream(f);
                    workbook.write(fis);
                    fis.close();
                    JOptionPane.showMessageDialog(null, "Save Thành Công");
                } catch (IOException ex) {
                    Logger.getLogger(NhanVienJframe.class.getName()).log(Level.SEVERE, null, ex);
                }

        }
  }
  
     
  public void hienthi2()
  {
      String timkiemString=jtfSerach.getText();
        ArrayList<HopDong> list=HopDongDao.gethienthiCSDL(timkiemString);
        dtmhd=(DefaultTableModel) tblHopDong.getModel();
        dtmhd.setRowCount(0);
        for(HopDong hd:list)
        {
            Vector<Object>vec=new Vector<>();
            vec.add(hd.getMAHD());
            vec.add(hd.getMaNV());
            vec.add(hd.getLoaiHD());
            vec.add(hd.getNgayBD());
            vec.add(hd.getNgayKT());
            vec.add(hd.isTinhTrang()== true ? "Còn" : "Nghĩ");
            dtmhd.addRow(vec);
        }

        tblHopDong.setModel(dtmhd);

  }
          
   public void hienthi()
           
   {
       
        ArrayList<HopDong> list=HopDongDao.laydachsachhd();
        dtmhd=(DefaultTableModel) tblHopDong.getModel();
        dtmhd.setRowCount(0);
       
        for(HopDong hd:list)
        {
            Vector<Object>vec=new Vector<>();
            vec.add(hd.getMAHD());
            vec.add(hd.getMaNV());
            vec.add(hd.getLoaiHD());
            vec.add(hd.getNgayBD());
            vec.add(hd.getNgayKT());
            vec.add(hd.isTinhTrang()== true ? "Còn" : "Nghĩ");
            dtmhd.addRow(vec);
        }

        tblHopDong.setModel(dtmhd);

   }

}
