package Gui;

import Dao.DaoNhanVien;
import Dao.HopDongDao;
import Dao.PhongBanDao;
import Model.ChucVu;
import Model.NhanVien;
import Model.PhongBan;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFChartSheet;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;



/**
 *
 * @author TVD
 */
public class NhanVienJframe extends javax.swing.JFrame {
    NhanVien nhanVien=null;
    PhongBan phongBan=null;
     DaoNhanVien tt= new DaoNhanVien();
     JFileChooser filechooser;
    public NhanVienJframe(NhanVien nhanVien) {
        initComponents();
        loadcombox();
        loadcombox2();
          filechooser=new JFileChooser();
         filechooser.setFileFilter(new FileFilter() {
            @Override
            public boolean accept(File f) {
                return f.getAbsolutePath().endsWith(".xlsx");
            }
            @Override
            public String getDescription() {
                   return "node .xlsx";
            }
        }); 
        
       
     
//       
//           ArrayList<PhongBan> dspb= DaoNhanVien.loadcombox();
        setView(nhanVien);
      
    }
    public void setView(NhanVien nhanVien)
    {
        this.nhanVien=nhanVien;
//        this.phongBan=phongBan;
//        NhanVien nv=new NhanVien();
        jtfManv.setText(nhanVien.getMANV());
        jtfhoten.setText(nhanVien.getHoTen());
         jtfNgaySinh.setText(nhanVien.getNGSINH());
        if (nhanVien.isGIOITINH()) {
            jdNam.setSelected(true);
            JdNu.setSelected(false);
        } else {
            jdNam.setSelected(false);
            JdNu.setSelected(true);
        }
        jtfDiachi.setText(nhanVien.getDiaChi());
        jtfSodt.setText(nhanVien.getSODT());
        jcom.setSelectedItem(nhanVien.getMAPB());
        jcom2.setSelectedItem(nhanVien.getMACV());
         jtfNgaySinh.setText(nhanVien.getNGSINH());
        if (nhanVien.isTinhTrang()) {
            jdCon.setSelected(true);
            jdNghi.setSelected(false);
        } else {
            jdCon.setSelected(false);
            jdNghi.setSelected(true);
        }
//        jcbCv.setSelectedItem(phongBan.ge())
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfManv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfhoten = new javax.swing.JTextField();
        jdNam = new javax.swing.JRadioButton();
        JdNu = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jtfSodt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtfDiachi = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtfNgaySinh = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jdCon = new javax.swing.JRadioButton();
        jdNghi = new javax.swing.JRadioButton();
        jcom = new javax.swing.JComboBox<PhongBan
        >();
        jcom2 = new javax.swing.JComboBox<ChucVu>();
        jlbMsg = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnThem.setBackground(new java.awt.Color(76, 175, 80));
        btnThem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-downloading-updates-32.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setBorder(null);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin học viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Mã học viên:");

        jtfManv.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtfManv.setForeground(new java.awt.Color(255, 51, 51));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Họ và tên:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Ngày sinh:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Giới tính:");

        jtfhoten.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        buttonGroup1.add(jdNam);
        jdNam.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jdNam.setSelected(true);
        jdNam.setText("Nam");

        buttonGroup1.add(JdNu);
        JdNu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        JdNu.setText("Nữ");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Số điện thoại:");

        jtfSodt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Địa chỉ:");

        jtfDiachi.setColumns(20);
        jtfDiachi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtfDiachi.setLineWrap(true);
        jtfDiachi.setRows(5);
        jScrollPane1.setViewportView(jtfDiachi);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Ma Phong Ban");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Ma Chuc vu");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Tình Trạng");

        buttonGroup2.add(jdCon);
        jdCon.setSelected(true);
        jdCon.setText("Còn");

        buttonGroup2.add(jdNghi);
        jdNghi.setText("Nghĩ");

        jcom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcom2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtfNgaySinh, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfManv, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(jtfhoten, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(27, 27, 27)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtfSodt)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jdCon)
                                .addGap(18, 18, 18)
                                .addComponent(jdNghi))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jdNam)
                                .addGap(18, 18, 18)
                                .addComponent(JdNu))
                            .addComponent(jcom, 0, 159, Short.MAX_VALUE)
                            .addComponent(jcom2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfManv, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfSodt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfhoten, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdNam)
                            .addComponent(JdNu)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel8)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jdCon)
                    .addComponent(jdNghi))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jcom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        jlbMsg.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlbMsg.setForeground(new java.awt.Color(255, 0, 0));

        jButton1.setBackground(new java.awt.Color(153, 255, 102));
        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-cancel-33.png"))); // NOI18N
        jButton1.setText("Xoa");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(255, 204, 0));
        btnSua.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-insert-page-32.png"))); // NOI18N
        btnSua.setText("Sữa");
        btnSua.setBorder(null);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnPrint.setBackground(new java.awt.Color(255, 255, 51));
        btnPrint.setText("Xuat file Excel");
        btnPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrintMouseClicked(evt);
            }
        });
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSua))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
       
     
             if(tt.kiemtramatontai(jtfManv.getText()))
                    
                {
                    JOptionPane.showMessageDialog(null,"MÃ:" +jtfManv.getText(),"Đã Tồn tại",
                 JOptionPane.WARNING_MESSAGE);
                }
    else
    {
        
      
                  nhanVien.setMANV(jtfManv.getText());
                nhanVien.setHoTen(jtfhoten.getText());
                nhanVien.setGIOITINH(jdNam.isSelected());
                nhanVien.setNGSINH(jtfNgaySinh.getText());
                nhanVien.setDiaChi(jtfDiachi.getText());
                nhanVien.setMAPB(jcom.getSelectedItem()+"");
                nhanVien.setMACV(jcom2.getSelectedItem()+"");
                nhanVien.setTinhTrang(jdCon.isSelected());
                int n=JOptionPane.showConfirmDialog(null, "Ban Muốn Thêm Không","Thêm",JOptionPane.YES_OPTION);
           if(n==JOptionPane.YES_OPTION)
           {
               tt.ThemNhanVien(nhanVien);
//               tt.layDachSachNV();
               JOptionPane.showMessageDialog(null, "thêm thành công");
          }
        }
        
       
    
          
    }//GEN-LAST:event_btnThemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        HopDongDao tt=new HopDongDao();
        DaoNhanVien tt2=new DaoNhanVien();
           if(tt.kiemtrakhoangoai(jtfManv.getText()))
        {
        JOptionPane.showMessageDialog(null,"Không Được Xóa" +"Bạn Phải Xóa MÃ HD có MÃ NV: "+jtfManv.getText()+"Trước");
        }
           else
           {
       nhanVien.setMANV(jtfManv.getText());
                int n=JOptionPane.showConfirmDialog(null, "Ban Muốn Xóa Không","Xóa",JOptionPane.YES_OPTION);
           if(n==JOptionPane.YES_OPTION)
           {
               tt2.XoaNhanVien(nhanVien);
               tt2.layDachSachNV();
               JOptionPane.showMessageDialog(null, "Xóa thành công");
                
           }
           }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        DaoNhanVien tt=new DaoNhanVien();
            if(tt.kiemtramatontai(jtfManv.getText())==false)
            {
                nhanVien.setMANV(jtfManv.getText());
                nhanVien.setHoTen(jtfhoten.getText());
                nhanVien.setGIOITINH(jdNam.isSelected());
                nhanVien.setNGSINH(jtfNgaySinh.getText());
                nhanVien.setDiaChi(jtfDiachi.getText());
                nhanVien.setSODT(jtfSodt.getText());
                nhanVien.setMAPB(jcom.getSelectedItem()+"");
                nhanVien.setMACV(jcom2.getSelectedItem()+"");
                nhanVien.setTinhTrang(jdCon.isSelected());
            
                int n=JOptionPane.showConfirmDialog(null, "Ban Muốn sữa Không","Sữa",JOptionPane.YES_OPTION);
           if(n==JOptionPane.YES_OPTION)
           {
               tt.updateNhanVien(nhanVien);
               tt.layDachSachNV();
               JOptionPane.showMessageDialog(null, "update thành công");
                
           }
            }
            else{
                JOptionPane.showMessageDialog(null, "Không được sữa Mã NV ");
            }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnPrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintMouseClicked
            xuatFileExcel();
  
    }//GEN-LAST:event_btnPrintMouseClicked

    private void jcom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcom2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcom2ActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrintActionPerformed
public void loadcombox()
{
//    ArrayList<PhongBan> dspb=DaoNhanVien.loadcombox();
       
        jcom.removeAllItems();
        ArrayList<PhongBan> dspb=DaoNhanVien.loadcombox();
        for (PhongBan n:dspb){
            jcom.addItem(n);
        }
        
        }

public void loadcombox2()
{
    jcom2.removeAllItems();
        ArrayList<ChucVu> dspb=DaoNhanVien.laydschucvu();
        for (ChucVu n:dspb){
            jcom2.addItem(n);
        }
        
        }
    


public void xuatFileExcel()
{
        
            XSSFWorkbook workbook = new XSSFWorkbook();
            XSSFSheet sheet = workbook.createSheet("Học Viên");
            
            XSSFRow row = null;
            Cell cell = null;
            
            row = sheet.createRow(0);
            
            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("STT");
            
            cell = row.createCell(1, CellType.STRING);
            cell.setCellValue("Họ và tên");
            
            cell = row.createCell(2, CellType.STRING);
            cell.setCellValue("Ngày sinh");
            
            cell = row.createCell(3, CellType.STRING);
            cell.setCellValue("Giới tính");
            
            cell = row.createCell(4, CellType.STRING);
            cell.setCellValue("Địa Chỉ");
            
            cell = row.createCell(5, CellType.STRING);
            cell.setCellValue("Số Điện Thoại");
            
            cell = row.createCell(6, CellType.STRING);
            cell.setCellValue("Mã Phòng Ban");
            
            cell = row.createCell(7, CellType.STRING);
            cell.setCellValue("Mã Phòng Ban");
            
            cell = row.createCell(8, CellType.STRING);
            cell.setCellValue("Mã Chức Vụ");
            
            cell = row.createCell(9, CellType.STRING);
            cell.setCellValue("Tình Trạng");
            
            ArrayList<NhanVien> listItem=DaoNhanVien.layDachSachNV();
//                List<> listItem = hocVienService.getList();;

if (listItem != null) {
    
    try {
        int s = listItem.size();
        for (int i = 0; i < s; i++) {
            NhanVien nhanVien = listItem.get(i);
            this.nhanVien=nhanVien;
            row = sheet.createRow(1 + i);
            
            
            cell = row.createCell(0, CellType.NUMERIC);
            cell.setCellValue(i + 1);
            
            cell = row.createCell(1, CellType.STRING);
            cell.setCellValue(nhanVien.getMANV());
            
            cell = row.createCell(2, CellType.STRING);
            cell.setCellValue(nhanVien.getHoTen());
            
            cell = row.createCell(3, CellType.STRING);
            cell.setCellValue(nhanVien.getNGSINH());
            
            cell = row.createCell(4, CellType.STRING);
            cell.setCellValue(nhanVien.isGIOITINH() ? "Nam" : "Nữ");
            
            cell = row.createCell(5, CellType.STRING);
            cell.setCellValue(nhanVien.getDiaChi());
            
            cell = row.createCell(6, CellType.STRING);
            cell.setCellValue(nhanVien.getSODT());
            
            cell = row.createCell(7, CellType.STRING);
            cell.setCellValue(nhanVien.getMAPB());
            
            cell = row.createCell(8, CellType.STRING);
            cell.setCellValue(nhanVien.getMACV());
            
            cell = row.createCell(9, CellType.STRING);
            cell.setCellValue(nhanVien.isTinhTrang() ?"Còn":"Hết");
        }
        // save file
        
    } catch (Exception ex) {
        ex.printStackTrace();
    }
}
  if(filechooser.showSaveDialog(null)==JFileChooser.APPROVE_OPTION){
                try {
                    FileOutputStream fis = null;
                    File f = new File(filechooser.getSelectedFile().toString());
                    fis = new FileOutputStream(f);
                    workbook.write(fis);
                    fis.close();
                    JOptionPane.showMessageDialog(null, "Save Thành Công");
                } catch (IOException ex) {
                    Logger.getLogger(NhanVienJframe.class.getName()).log(Level.SEVERE, null, ex);
                }

        }
             
                        
                
                        }
                        
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton JdNu;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<PhongBan
    > jcom;
    private javax.swing.JComboBox<ChucVu> jcom2;
    private javax.swing.JRadioButton jdCon;
    private javax.swing.JRadioButton jdNam;
    private javax.swing.JRadioButton jdNghi;
    private javax.swing.JLabel jlbMsg;
    private javax.swing.JTextArea jtfDiachi;
    private javax.swing.JTextField jtfManv;
    private javax.swing.JTextField jtfNgaySinh;
    private javax.swing.JTextField jtfSodt;
    private javax.swing.JTextField jtfhoten;
    // End of variables declaration//GEN-END:variables
}
