/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Dao.DBConnect;
import Dao.DaoChucvu;
import Dao.DaoNhanVien;
import Dao.PhongBanDao;
import Model.ChucVu;
import Model.Luong;
import Model.NhanVien;
import Model.PhongBan;
import java.awt.Dimension;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author TVD
 */
public class NhanVienJPanel extends javax.swing.JPanel {
 private TableRowSorter<TableModel> rowSorter = null;
    DefaultTableModel dtmnv;
    DefaultTableModel dtmcv;
    ChucVu cv=new ChucVu();
    
    /**
     * Creates new form KhoaHocJPanel
     */ 
    NhanVien nhanVien =new NhanVien();
    public NhanVienJPanel() {
        initComponents();
        hienthi();
        hienthicv();
        loadcombox();
                       
                            tbNhanVien.setModel(dtmnv);
                    rowSorter = new TableRowSorter<>(tbNhanVien.getModel());
        tbNhanVien.setRowSorter(rowSorter);
        tbNhanVien.getColumnModel().getColumn(0).setMinWidth(0);
        tbNhanVien.getColumnModel().getColumn(0).setMaxWidth(150);
        tbNhanVien.getColumnModel().getColumn(0).setPreferredWidth(150);
        
        tbNhanVien.getColumnModel().getColumn(1).setMinWidth(0);
        tbNhanVien.getColumnModel().getColumn(1).setMaxWidth(150);
        tbNhanVien.getColumnModel().getColumn(1).setPreferredWidth(150);
        
         tbNhanVien.getTableHeader().setFont(new Font("Arrial", Font.BOLD, 14));
        tbNhanVien.getTableHeader().setPreferredSize(new Dimension(100, 50));
        tbNhanVien.setRowHeight(50);
        tbNhanVien.validate();
        tbNhanVien.repaint();      
                        
         jtfSerach.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = jtfSerach.getText();
                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = jtfSerach.getText();
                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
            }
          
         });        
         
          
                            tblChucvu.setModel(dtmcv);
                    rowSorter = new TableRowSorter<>(tblChucvu.getModel());
        tblChucvu.setRowSorter(rowSorter);
        tblChucvu.getColumnModel().getColumn(0).setMinWidth(0);
        tblChucvu.getColumnModel().getColumn(0).setMaxWidth(150);
        tblChucvu.getColumnModel().getColumn(0).setPreferredWidth(150);
        
        tblChucvu.getColumnModel().getColumn(1).setMinWidth(0);
        tblChucvu.getColumnModel().getColumn(1).setMaxWidth(150);
        tblChucvu.getColumnModel().getColumn(1).setPreferredWidth(150);
        
         tblChucvu.getTableHeader().setFont(new Font("Arrial", Font.BOLD, 14));
        tblChucvu.getTableHeader().setPreferredSize(new Dimension(100, 50));
        tblChucvu.setRowHeight(50);
        tblChucvu.validate();
        tblChucvu.repaint();      
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbNhanVien = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtfSerach = new javax.swing.JTextField();
        btnHienthi = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChucvu = new javax.swing.JTable();
        jtfcv = new javax.swing.JTextField();
        jtcTencv = new javax.swing.JTextField();
        jcom = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 255, 0));
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });

        tbNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Nhân Viên", "Họ Tên Nhân Viên", "Ngày Sinh", "Giới Tính", "Địa Chỉ", "Số Điện Thoại ", "Mã Phòng Ban", "Mã Chức  Vụ", "TinhTrang"
            }
        ));
        tbNhanVien.setDropMode(javax.swing.DropMode.ON);
        tbNhanVien.getTableHeader().setResizingAllowed(false);
        tbNhanVien.getTableHeader().setReorderingAllowed(false);
        tbNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbNhanVienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbNhanVien);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-zoom-in-34.png"))); // NOI18N
        jLabel1.setText("Tìm Kiêm");

        btnHienthi.setBackground(new java.awt.Color(255, 255, 255));
        btnHienthi.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnHienthi.setForeground(new java.awt.Color(0, 255, 0));
        btnHienthi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-eye-35.png"))); // NOI18N
        btnHienthi.setText("Hiển Thị");
        btnHienthi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienthiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(386, 386, 386)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfSerach, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(btnHienthi)))
                .addGap(99, 181, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfSerach, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(btnHienthi)))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jTabbedPane1.addTab("Dach Sach Nhan Vien", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 153, 102));

        tblChucvu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Chức Vụ", "Tên Chức Vụ", "Hệ Số Lương"
            }
        ));
        tblChucvu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChucvuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblChucvu);

        jcom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Mã Chức Vụ");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Tên Chức Vụ");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Hệ Số Lương");

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-insert-page-32.png"))); // NOI18N
        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 255, 153));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-downloading-updates-32.png"))); // NOI18N
        jButton2.setText("Sữa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 255, 255));
        jButton3.setForeground(new java.awt.Color(255, 204, 51));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-cancel-33.png"))); // NOI18N
        jButton3.setText("Xóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 204));
        jButton4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-zoom-in-34.png"))); // NOI18N
        jButton4.setText("Hiển Thị");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addComponent(jtfcv, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(62, 62, 62)
                        .addComponent(jButton2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jtcTencv, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(44, 44, 44)
                        .addComponent(jcom, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButton4)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfcv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtcTencv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Quản Lý Chức Vụ", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

    }//GEN-LAST:event_formComponentShown

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
        // TODO add your handling code her:

    }//GEN-LAST:event_jPanel1ComponentShown

    private void btnHienthiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienthiActionPerformed

        hienthi();
    }//GEN-LAST:event_btnHienthiActionPerformed

    private void tbNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNhanVienMouseClicked

        int selectedRowIndex = tbNhanVien.getSelectedRow();
        selectedRowIndex = tbNhanVien.convertRowIndexToModel(selectedRowIndex);

        nhanVien.setMANV( dtmnv.getValueAt(selectedRowIndex, 0)+"");
        nhanVien.setHoTen(tbNhanVien.getValueAt(selectedRowIndex, 1)+"");
        nhanVien.setNGSINH( tbNhanVien.getValueAt(selectedRowIndex, 2)+"");
        nhanVien.setGIOITINH(tbNhanVien.getValueAt(selectedRowIndex, 3).toString().equalsIgnoreCase("Nam"));
        nhanVien.setDiaChi(tbNhanVien.getValueAt(selectedRowIndex, 4)+"");
        nhanVien.setSODT(tbNhanVien.getValueAt(selectedRowIndex, 5)+"");
        nhanVien.setMAPB(tbNhanVien.getValueAt(selectedRowIndex, 6)+"");
        nhanVien.setMACV(tbNhanVien.getValueAt(selectedRowIndex, 7)+"");
        nhanVien.setTinhTrang(tbNhanVien.getValueAt(selectedRowIndex, 8).toString().equalsIgnoreCase("Còn"));

        NhanVienJframe frame = new NhanVienJframe(nhanVien);
        frame.setTitle("Thông tin học viên");
        frame.setResizable(false);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }//GEN-LAST:event_tbNhanVienMouseClicked

    private void tblChucvuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChucvuMouseClicked
        // TODO add your handling code here:
        ChucVu cv=new ChucVu();
           int row =this.tblChucvu.getSelectedRow();
        this.jtfcv.setText(tblChucvu.getValueAt(row, 0)+"");
        this.jtcTencv.setText(tblChucvu.getValueAt(row, 1)+"");
      
         
      
        
    }//GEN-LAST:event_tblChucvuMouseClicked

    private void jcomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed



        // TODO add your handling code here:
        DaoChucvu tt= new DaoChucvu();
            cv.setMacv(jtfcv.getText());
            cv.setTencv(jtcTencv.getText());
           
            if(tt.kiemtramatontai2(jtfcv.getText()))
            {
                JOptionPane.showMessageDialog(null, "trùng mã");
            }
            else
            {
           cv.setHsl(Float.parseFloat(jcom.getSelectedItem().toString()));
                int n=JOptionPane.showConfirmDialog(null, "ban muon then","Them",JOptionPane.YES_OPTION);
                if(n==JOptionPane.YES_OPTION)
                        {
                            
                            tt.themluongnv(cv);
                            hienthi();
                            JOptionPane.showMessageDialog(null, "thêm ok");
                        }
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DaoChucvu tt= new DaoChucvu();
            cv.setMacv(jtfcv.getText());
            cv.setTencv(jtcTencv.getText());
           
           
          
            
           cv.setHsl(Float.parseFloat(jcom.getSelectedItem().toString()));
                int n=JOptionPane.showConfirmDialog(null, "ban muon sữa ","sữa",JOptionPane.YES_OPTION);
                if(n==JOptionPane.YES_OPTION)
                        {
                            
                            tt.updateluongnv(cv);
                            hienthi();
                            JOptionPane.showMessageDialog(null, "sữa ok");
                                    
                        }
        
            
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DaoChucvu tt= new DaoChucvu();
            cv.setMacv(jtfcv.getText());
                if(tt.kiemtramatontai(jtfcv.getText()))
                {
                    JOptionPane.showMessageDialog(null, "k được xóa phải xóa mã nhân viên có cv:"+jtfcv.getText());
                }
                else{
                int n=JOptionPane.showConfirmDialog(null, "ban muon Xóa","Xóa",JOptionPane.YES_OPTION);
                if(n==JOptionPane.YES_OPTION)
                        {
                            
                            tt.delteluongnv(cv);
                            hienthi();
                            JOptionPane.showMessageDialog(null,"xóa ok");
                        }
                }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        hienthicv();;
    }//GEN-LAST:event_jButton4ActionPerformed

public void hienthi()
{
      ArrayList<NhanVien> list = DaoNhanVien.layDachSachNV();
//         loadcombox();
                       dtmnv=(DefaultTableModel) tbNhanVien.getModel();
                       
                        dtmnv.setRowCount(0);
                        for(NhanVien nv:list)
                        {
                            Vector<Object>vec=new Vector<>();
                          vec.add(nv.getMANV());
                          vec.add(nv.getHoTen());
                          vec.add(nv.getNGSINH());
                          vec.add((nv.isGIOITINH())== true ? "Nam" : "Nữ");
                          vec.add(nv.getDiaChi());
                          vec.add(nv.getSODT());
                           vec.add(nv.getMAPB());
                           vec.add((nv.getMACV()));
                           vec.add((nv.isTinhTrang())== true ? "Còn":"Nghĩ");
                           
                            dtmnv.addRow(vec);
                        }
                      
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHienthi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<Luong> jcom;
    private javax.swing.JTextField jtcTencv;
    private javax.swing.JTextField jtfSerach;
    private javax.swing.JTextField jtfcv;
    private javax.swing.JTable tbNhanVien;
    private javax.swing.JTable tblChucvu;
    // End of variables declaration//GEN-END:variables

   public void hienthicv()
   {ArrayList<ChucVu> list =DaoChucvu.laydschucvu();
//         loadcombox();
                       dtmcv=(DefaultTableModel) tblChucvu.getModel();
                       
                        dtmcv.setRowCount(0);
                        for(ChucVu cv:list)
                        {
                            Vector<Object>vec=new Vector<>();
                          vec.add(cv.getMacv());
                         vec.add(cv.getTencv());
                         vec.add(cv.getHsl());
                            dtmcv.addRow(vec);
                        }
                                              tblChucvu.setModel(dtmcv);
                    rowSorter = new TableRowSorter<>(tblChucvu.getModel());
        tblChucvu.setRowSorter(rowSorter);
        tblChucvu.getColumnModel().getColumn(0).setMinWidth(0);
        tblChucvu.getColumnModel().getColumn(0).setMaxWidth(150);
        tblChucvu.getColumnModel().getColumn(0).setPreferredWidth(150);
        
        tblChucvu.getColumnModel().getColumn(1).setMinWidth(0);
        tblChucvu.getColumnModel().getColumn(1).setMaxWidth(150);
        tblChucvu.getColumnModel().getColumn(1).setPreferredWidth(150);
        
         tblChucvu.getTableHeader().setFont(new Font("Arrial", Font.BOLD, 14));
        tblChucvu.getTableHeader().setPreferredSize(new Dimension(100, 50));
        tblChucvu.setRowHeight(50);
        tblChucvu.validate();
        tblChucvu.repaint();      
                        
       
   }
   public void loadcombox()
   {
       jcom.removeAll();
       ArrayList<Luong> dscv=DaoChucvu.laydsluongloadcombox();
       for(Luong n:dscv){
          jcom.addItem(n);
       }
               
   }
}
