/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Dao.DBConnect;
import Dao.DaoNhanVien;
import Dao.PhongBanDao;
import Model.ChucVu;
import Model.NhanVien;
import Model.PhongBan;
import java.awt.Dimension;
import java.awt.Font;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author TVD
 */
public class PhongBanJPanel1 extends javax.swing.JPanel {
   private PhongBan  phongBan= new PhongBan();
     private PhongBanDao phongBanDao=new PhongBanDao();
    private TableRowSorter<TableModel> rowSorter = null;
    JFileChooser  filechooser;
 DefaultTableModel dtmpb=null;
    /**
     * Creates new form KhoaHocJPanel
     */ PhongBan nhomTenPBan;
    public PhongBanJPanel1() {
        initComponents();
       hienthi();
       loadcombox();
          filechooser=new JFileChooser();
         filechooser.setFileFilter(new FileFilter() {
            @Override
            public boolean accept(File f) {
                return f.getAbsolutePath().endsWith(".xlsx");
            }
            @Override
            public String getDescription() {
                   return "node .xlsx";
            }
        }); 
                      
                       
                            
                    rowSorter = new TableRowSorter<>(tblPhongban.getModel());
        tblPhongban.setRowSorter(rowSorter);
        tblPhongban.getColumnModel().getColumn(0).setMinWidth(170);
        tblPhongban.getColumnModel().getColumn(0).setMaxWidth(170);
        tblPhongban.getColumnModel().getColumn(0).setPreferredWidth(170);
        
        tblPhongban.getColumnModel().getColumn(1).setMinWidth(170);
        tblPhongban.getColumnModel().getColumn(1).setMaxWidth(170);
        tblPhongban.getColumnModel().getColumn(1).setPreferredWidth(170);
        
         tblPhongban.getTableHeader().setFont(new Font("Arrial", Font.BOLD, 14));
        tblPhongban.getTableHeader().setPreferredSize(new Dimension(100, 50));
        tblPhongban.setRowHeight(50);
        tblPhongban.validate();
        tblPhongban.repaint();  
          
                        
                        
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPhongban = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtfMaPB = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfSDT = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtfDiacHi = new javax.swing.JTextField();
        jtfTenPhong = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jcom = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tblPhongban.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Phòng Ban", "Tên Phòng Ban", "Địa Chỉ", "Số Điện Thoại PB"
            }
        ));
        tblPhongban.setDropMode(javax.swing.DropMode.ON);
        tblPhongban.getTableHeader().setResizingAllowed(false);
        tblPhongban.getTableHeader().setReorderingAllowed(false);
        tblPhongban.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhongbanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPhongban);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Mã Phòng Ban");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Tên Phòng Ban");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Số Điện Thoại");

        jtfSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSDTActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(255, 255, 0));
        btnThem.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-add-row-32.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 153, 0));
        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-downloading-updates-32.png"))); // NOI18N
        jButton2.setText("Sữa");
        jButton2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 0));
        jButton4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-cancel-33.png"))); // NOI18N
        jButton4.setText("Xóa");
        jButton4.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton4AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Địa Chỉ");

        jtfDiacHi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDiacHiActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-zoom-in-34.png"))); // NOI18N
        jButton1.setText("Tìm Kiêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 51, 0));
        jButton3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-eye-35.png"))); // NOI18N
        jButton3.setText("Hiển Thị");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 204, 255));
        jButton5.setText("Xuất File Excel");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jcom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Mã Cv:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jScrollPane2)
                .addGap(2, 2, 2))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jtfMaPB, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtfDiacHi, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(31, 31, 31)
                        .addComponent(jtfTenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(46, 46, 46)
                        .addComponent(jButton5)
                        .addGap(13, 13, 13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jcom, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(btnThem)
                .addGap(69, 69, 69)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtfDiacHi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jtfMaPB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtfTenPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jtfSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(23, 23, 23))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnThem)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Dach Sách Phòng Ban", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSDTActionPerformed

    private void tblPhongbanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhongbanMouseClicked
     
      
        int rowindex=this.tblPhongban.getSelectedRow();
        this.jtfMaPB.setText(tblPhongban.getValueAt(rowindex, 0)+"");
        this.jtfTenPhong.setText(tblPhongban.getValueAt(rowindex,1)+"");
        this.jtfDiacHi.setText(tblPhongban.getValueAt(rowindex, 2)+"");
        this.jtfSDT.setText(tblPhongban.getValueAt(rowindex, 3)+"");
        //        this.txtMa.setText((String) tblql.getValueAt(row, 0));
        //        this.txtTieude.setText((String) tblql.getValueAt(row, 1));
        //        this.jcomloainhomSelected = (nhomKhachHang)cbox_nhomKH.getSelectedItem();
    }//GEN-LAST:event_tblPhongbanMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
            ThempbJdalog tt=new ThempbJdalog(null, true);
        tt.setTitle("Thêm Phòng Ban");
                    tt.setResizable(false);
                    tt.setLocationRelativeTo(null);
                    tt.setVisible(true);
                       
                       
//                       this.phongBan=phongBan;
//                phongBan.setMapb(jtfMaPB.getText());
//                phongBan.setTenpb(jtfTenPhong.getText());
//                phongBan.setDiachi(jtfDiacHi.getText());
//                phongBan.setSdtpb(jtfSDT.getText());
//                
//        
//        
//        int n=JOptionPane.showConfirmDialog(null, "ban muon them k","them",JOptionPane.YES_OPTION);
//                if(n==JOptionPane.YES_OPTION)
//                        {
//                            phongBanDao.ThemNhanVien(phongBan);
//                        }
               
    }//GEN-LAST:event_btnThemActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//               int row =this.tblPhongban.getSelectedRow();
//        int selectedRowIndex = tblPhongban.getSelectedRow();
//                 phongBan.setTenpb(tblPhongban.getValueAt(selectedRowIndex, 0)+"");
//        phongBan.setTenpb(tblPhongban.getValueAt(selectedRowIndex, 1)+"");
//        phongBan.setSdtpb(tblPhongban.getValueAt(selectedRowIndex, 2)+"");
       
                        
                     phongBan.setMapb(jtfMaPB.getText());
                phongBan.setDiachi(jtfDiacHi.getText());
                phongBan.setSdtpb(jtfSDT.getText());
                int n=JOptionPane.showConfirmDialog(null, "ban muốn sửa không","Sữa",JOptionPane.YES_OPTION);
                if(n==JOptionPane.YES_OPTION)
                        {
                           phongBanDao.updateNhanVien(phongBan);
                           JOptionPane.showMessageDialog(null, "them thanh cong");
                        }
                      
               
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton4AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4AncestorAdded

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        if(phongBanDao.kiemtrakhoangoai(jtfMaPB.getText()))
        {
           JOptionPane.showMessageDialog(null, "Phải Xóa Nhân Viên Có MÃ PB:" +jtfMaPB.getText()+" Mới Được Phép Xóa");
        }
        else
        {
        phongBan.setMapb(jtfMaPB.getText());
                   
                int n=JOptionPane.showConfirmDialog(null, "ban muốn Xóa Không","Xoa",JOptionPane.YES_OPTION);
                if(n==JOptionPane.YES_OPTION)
                        {
                           phongBanDao.XoaNhanPb(phongBan);
                           JOptionPane.showMessageDialog(null, "xoa thanh cong");
                        }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton2AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2AncestorAdded

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

    }//GEN-LAST:event_formComponentShown

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
        // TODO add your handling code her:

    }//GEN-LAST:event_jPanel1ComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TimKiem  jfKiem =new TimKiem();
        jfKiem.setTitle("Tìm Kiếm Phòng Ban");
                    jfKiem.setResizable(false);
                    jfKiem.setLocationRelativeTo(null);
                    jfKiem.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        hienthi();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        
   xuatFileExcle();
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jcomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomActionPerformed

    private void jtfDiacHiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDiacHiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDiacHiActionPerformed

public void xuatFileExcle()
{
     XSSFWorkbook workbook = new XSSFWorkbook();
                XSSFSheet sheet = workbook.createSheet("Học Viên");

                XSSFRow row = null;
                Cell cell = null;

                row = sheet.createRow(0);

               cell = row.createCell(0, CellType.STRING);
                cell.setCellValue("STT");

                cell = row.createCell(1, CellType.STRING);
                cell.setCellValue("Mã Phòng Ban");

                cell = row.createCell(2, CellType.STRING);
                cell.setCellValue("Tên Phòng Ban");
                
                 cell = row.createCell(3, CellType.STRING);
                cell.setCellValue("Địa Chỉ Phòng Ban");
                
                cell = row.createCell(4, CellType.STRING);
                cell.setCellValue("Số Đt Phòng Ban");
                
                ArrayList<PhongBan> listItem=phongBanDao.layDachSachPB();
//                List<> listItem = hocVienService.getList();;

                if (listItem != null) {
                    FileOutputStream fis = null;
                    try {
                        int s = listItem.size();
                        for (int i = 0; i < s; i++) {
                            PhongBan phongBan = listItem.get(i);
                              this.phongBan= phongBan;
                            row = sheet.createRow(1 + i);

                          
                            cell = row.createCell(0, CellType.NUMERIC);
                            cell.setCellValue(i + 1);

                            cell = row.createCell(1, CellType.STRING);
                            cell.setCellValue(phongBan.getMapb());

                            cell = row.createCell(2, CellType.STRING);
                            cell.setCellValue(phongBan.getTenpb());

                            cell = row.createCell(3, CellType.STRING);
                            cell.setCellValue(phongBan.getDiachi());

                            cell = row.createCell(4, CellType.STRING);
                                cell.setCellValue(phongBan.getSdtpb());
                      }
                        // save file
                       
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                }
                  if(filechooser.showSaveDialog(null)==JFileChooser.APPROVE_OPTION){
                try {
                    FileOutputStream fis = null;
                    File f = new File(filechooser.getSelectedFile().toString());
                    fis = new FileOutputStream(f);
                    workbook.write(fis);
                    fis.close();
                    JOptionPane.showMessageDialog(null, "Save Thành Công");
                } catch (IOException ex) {
                    Logger.getLogger(NhanVienJframe.class.getName()).log(Level.SEVERE, null, ex);
                }

        }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<ChucVu> jcom;
    private javax.swing.JTextField jtfDiacHi;
    private javax.swing.JTextField jtfMaPB;
    private javax.swing.JTextField jtfSDT;
    private javax.swing.JTextField jtfTenPhong;
    private javax.swing.JTable tblPhongban;
    // End of variables declaration//GEN-END:variables

    
    public void loadcombox()
    {
        
    {
       jcom.removeAllItems();
        ArrayList<ChucVu> list=phongBanDao.loadcombox();
        for(ChucVu n:list)
        {
            jcom.addItem(n);
        }
    }
    }
    private void hienthi() {
         ArrayList<PhongBan> list = phongBanDao.layDachSachPB();
//         loadcombox();
                       dtmpb=(DefaultTableModel) tblPhongban.getModel();
                        dtmpb.setRowCount(0);
                        for(PhongBan pb:list)
                        {
                            Vector<Object>vec=new Vector<>();
                          vec.add(pb.getMapb());
                          vec.add(pb.getTenpb());
                          vec.add(pb.getDiachi());
                           vec.add(pb.getSdtpb());
//                           vec.add(pb.getMAcv());
                            
                            dtmpb.addRow(vec);
                        }
                        tblPhongban.setModel(dtmpb);
    }

   
   

}
